/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Artistic_side (https://sketchfab.com/leorehman333)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-butterfly-d4fbcbaab845402999f30c5aa75851e6
Title: Animated Butterfly
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import insectScene from "../assets/animated_butterfly.glb";

const Insect = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(insectScene);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.Flying.timeScale = 0.4;
    actions.Flying.play();
  }, []);

  return (
    <group ref={group} {...props}>
      <group name='Sketchfab_Scene'>
        <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
          <group name='root'>
            <group name='GLTF_SceneRootNode' rotation={[Math.PI / 2, 0, 0]}>
              <group name='Armature_55'>
                <group name='GLTF_created_0'>
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name='Object_7'
                    geometry={nodes.Object_7.geometry}
                    material={materials.Wings}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name='Object_9'
                    geometry={nodes.Object_9.geometry}
                    material={materials.Wings}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  {/* <skinnedMesh
                    name='Object_11'
                    geometry={nodes.Object_11.geometry}
                    material={materials["Material.001"]}
                    skeleton={nodes.Object_11.skeleton}
                  /> */}
                  <group name='Plane_52' />
                  <group name='Plane001_53' />
                  <group name='Plane002_54' />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

// useGLTF.preload("/animated_butterfly.glb");

export default Insect;
